# Generated by Django 5.2.1 on 2025-06-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
